### ISSUE TITLE
Projects needs an update

### ISSUE THREAD

**Issue by ghost** [schneidsDotNet/AspNetPagingExample#1]
I am working on a custom API for our ERP for integrating data to multiple external cloud apps. I've been working with your AspNetPagingExample, and have updated all the NuGet packages to the latest release, but AutoMapper has moved on; and no longer compiles. I'm new to AutoMapper, but after a couple of days struggling, I don't think I'm getting anywhere.  Would you consider updating the example project to latest releases?

**Comment by schneidenbach** [comment]
Can you attach a sample project and/or tell me the compile errors you're seeing?  I'm guessing it has to do with using AutoMapper's static API vs its instance API.

Check out this page and see if it helps: https://github.com/AutoMapper/AutoMapper/wiki/Static-and-Instance-API

**Comment by ghost** [comment]
Here is my sample project

[AspNetPagingExample-instance.zip](https://github.com/schneidenbach/AspNetPagingExample/files/1362813/AspNetPagingExample-instance.zip)
